name: Hello, World!
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: dev
      run: |
        sam build 
        sam deploy --config-env dev
    
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Echo Hello, World!
      run: echo "Hello, World! Test"
  
  prod:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Echo Hello, World!
      run: echo "Hello, World!Production"
